---
# tasks file for first_role
- name: Install the latest version of apache # sudo yum install httpd
  yum:
    name: httpd
    state: latest
# ansible localhost -m yum -a "name=httpd state=latest"

- name: start the httpd service, if not started # sudo systemctl start httpd
  service:
    name: httpd
    state: started
    enabled: true

- name: remove index file, if created # /var/www/html/index.html
  file:
    path: /var/www/html/index.html
    state: absent

- name: add index file # /var/www/html/index.html
  file:
    path: /var/www/html/index.html
    state: touch

- name: add line in file
  lineinfile:
    path: /var/www/html/index.html
    line: <h1> This is {{ myName }}'s website! {{ line }} </h1> #Jinja templating {{ }}
